### ISSUE TITLE
How to train LLM of Huggingface?

### ISSUE THREAD

**Issue by yipliu** [Yongtae723/LLMFlowOptimizer#27]
Hi Yongtae,

I'm sorry for asking a question in your repository that has nothing to do with the repository. 

Recently, I attempted to use BART (I modified it). Despite setting the `batch_size to 1` on my 3090, I encountered a 'CUDA Out of Memory' error. 

Fortunately, I have multiple 3090 graphics cards on my computer. However, I'm not sure how to solve my problem in Lightning. Since my model still cannot run with a `batch size of 1`, DDP mode is not usable in this case. 

Do you have any suggestions?

**Comment by Yongtae723** [comment]
Hi 
Thank you for comment.

But unfortunately I have no idea😖

**Comment by yipliu** [comment]
Hi 
I have recently discovered `DeepSpeed` and am currently in the process of learning about it.

I am uncertain whether this library will be beneficial for my needs or not.

Thank you very much for open-sourcing this template. It will be incredibly helpful for my future studies in the field of NLP.
